import type { Metadata } from "next";
import localFont from "next/font/local";
import { AuthProvider } from '@/context/AuthContext';
import { Geist_Mono } from "next/font/google";
import "../styles/globals.css";

const afacad = localFont({
  src: "../styles/fonts/Afacad/Afacad-VariableFont_wght.ttf",
  variable: "--font-afacad",
  display: "swap",
  weight: "100 900",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/VL_Logo.svg",
    shortcut: "/VL_Logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${afacad.variable} ${geistMono.variable} h-full antialiased`}
    >
      <AuthProvider>
        <body className="min-h-full flex flex-col">{children}</body>
      </AuthProvider>
    </html>
  );
}
