version: '3.9'
#VERY LIKELY NEEDS TO BE REVISED FOR OUR ENV AND IF ANY PACKAGE CHANGES OCCUR, SAME IS TRUE FOR BOTH FRONTEND AND BACKEND FILES.
services:
    #frontend
    frontend:
        build:
            context: ./Frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NEXT_PUBLIC_API_URL=http://localhost:8000
        depends_on:
            - backend
        networks:
            - app-network

    #Backend api
    backend:
        build:
            context: ./Backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/veridian
            - REDIS_URL=redis://redis:6379/0
            - OPENSEARCH_URL=http://opensearch:9200
            - S3_BUCKET_NAME=${S3_BUCKET_NAME}
            - JWT_SECRET=${JWT_SECRET}
            # BOTO3 / MINIO CONFIGURATION
            - STORAGE_PROVIDER=minio
            - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}       # Map MinIO user to AWS key
            - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD} # Map MinIO pass to AWS secret
            - AWS_S3_ENDPOINT_URL=http://minio:9000       # Critical: Points boto3 to the container
            - S3_BUCKET_NAME=${MINIO_BUCKET_NAME}
            - AWS_DEFAULT_REGION=${AWS_REGION}               # Boto3 requires a region structure even for MinIO
        depends_on:
            - postgres
            - redis
            - opensearch
            - minio
        networks:
            - app-network

    #Celery Worker
    #same image as backend
    celery-worker:
        build:
            context: ./Backend
            dockerfile: Dockerfile
        command: celery -A app.tasks.celery_app worker --loglevel=info
        environment:
            - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/veridian
            - REDIS_URL=redis://redis:6379/0
            - OPENSEARCH_URL=http://opensearch:9200
            - JWT_SECRET=${JWT_SECRET}
            # BOTO3 / MINIO CONFIGURATION
            - STORAGE_PROVIDER=minio
            - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}       # Map MinIO user to AWS key
            - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD} # Map MinIO pass to AWS secret
            - AWS_S3_ENDPOINT_URL=${STORAGE_URL}      # Critical: Points boto3 to the container
            - S3_BUCKET_NAME=${MINIO_BUCKET_NAME}
            - AWS_DEFAULT_REGION=${AWS_REGION}               # Boto3 requires a region structure even for MinIO
        depends_on:
            - backend
            - redis
            - postgres
        networks:
            - app-network

    postgres:
        image: postgres:16-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=veridian
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - app-network

    opensearch:
        image: opensearchproject/opensearch:2.11.0
        environment:
            - discovery.type=single-node
            - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
            - DISABLE_SECURITY_PLUGIN=true
        ports:
            - "9200:9200"
        volumes:
            - opensearch_data:/usr/share/opensearch/data
        networks:
            - app-network
    minio:
        image: minio/minio:latest
        ports:
            - "${MINIO_API_PORT}:${MINIO_API_PORT}"     # Dynamic API Port
            - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}" # Dynamic Web Dashboard Port
        volumes:
            - minio_data:/data
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        command: server /data --address ":${MINIO_API_PORT}" --console-address ":${MINIO_CONSOLE_PORT}"
        networks:
            - app-network

volumes:
    postgres_data:
    redis_data:
    opensearch_data:
    minio_data:

networks:
    app-network:
        driver: bridge