name: Availability check

on:
  schedule:
  - cron: "2-59/10 * * * *"

  workflow_dispatch:

jobs:
  check-availability:
    runs-on: ubuntu-latest

    steps:
      - name: Check availability
        run: |
          curl --fail --silent --show-error \
            --max-time 10 \
            --location \
            https://veritaslab.app
