name: Test Full Deployment on Azure

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./Backend
          push: true
          tags: ghcr.io/cos301-se-2026/veritas-lab-backend:${{ github.sha }}
      - uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/cos301-se-2026/veritas-lab-frontend:${{ github.sha }}
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56CD338B385F4779A7BC4676B29FB956 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BED7D1D0A9DC411E9AE99306D126609E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_02B6A6C1098B4F408E9DEBBC5971A95D }}
      - uses: azure/webapps-deploy@v3
        with:
          app-name: veritas-lab-api
          sitecontainers-config: >-
            [
              {
                "name": "main",
                "image": "ghcr.io/cos301-se-2026/veritas-lab-frontend:${{ github.sha }}",
                "targetPort": 3000,
                "isMain": true,
                "authType": "UserCredentials",
                "userName": "${{ secrets.GHCR_USERNAME }}",
                "passwordSecret": "${{ secrets.GHCR_PAT}}"
              },
              {
                "name": "backend",
                "image": "ghcr.io/cos301-se-2026/veritas-lab-backend:${{ github.sha }}",
                "targetPort": 8000,
                "isMain": false,
                "authType": "UserCredentials",
                "userName": "${{ secrets.GHCR_USERNAME }}",
                "passwordSecret": "${{ secrets.GHCR_PAT}}"
              }
            ]
